### ISSUE TITLE
Infografia  Actividad 4

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-irvinjs22620075#1]
[Infografia Conceptos y funciones de Librerias.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-irvinjs22620075/files/14563244/Infografia.Conceptos.y.funciones.de.Librerias.pdf)
IRVIN JIMENEZ SANCHEZ

**Comment by Nancy-0714** [comment]
Calificación 20, pero solo falto los gráficos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
